### ISSUE TITLE
Multi passwords inputs in one page

### ISSUE THREAD

**Issue by MohamedElNady** [IncentroBA/ToggleShowPassword#1]
Hello,
I have a problem i have 2 passwords attributes  one password and one below it for confirm password.
I try to set toggle widget put it's only work on 1 password input not the both, and if i added 2 toggle password the didn't work both of them.

**Comment by iamrob-nl** [comment]
Hi There,
Thanks for notifying me. I am on it.

**Comment by iamrob-nl** [comment]
A new version of the widget is available. As far as I have seen the widget now works fine with multiple instances.

**Comment by MohamedElNady** [comment]
Thanks for your help,
I'll recheck it and notify you :)
